# Generated by Django 4.2.27 on 2025-12-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_badge_badge__ada96f_idx_badge_badge_t_fe5ec8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
